### ISSUE TITLE
Automate repo creation for contributors

### ISSUE THREAD

**Issue by v1gnesh** [zopencommunity/meta#906]
### Feature Title

autorepo

### Feature Description & Current Pain Points

Currently, when someone wants to work on a `thingport`, a zopen admin has to manually create a repo and setup the necessary access to the new repo for the contributor.

With GH actions and a new issue template, this can be automated.

### Proposed Solution & Expected Behavior

Haven't checked if this exact code works but it uses [actions/github-script](https://github.com/actions/github-script) and GH CLI.

**issue-template.yaml:**
```yaml
name: Trigger Repository Creation
description: Use this template to request a new repository based on specific criteria.
title: "Create new repo for [Project Name]"
labels: ["repo-creation-request"]
body:
  - type: markdown
    attributes:
      value: |
        ### Guidelines
        - Use this template to request a new repository where the project name should be included in the title.
        - **Important**: Include the word "Trigger" in the title to activate the automation.

  - type: textarea
    id: repo-name
    attributes:
      label: Repository Name
      description: Please enter the desired name for the new repository.
      placeholder: Example: my-new-project
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the purpose or content of the repository.
    validations:
      required: false
```

**create-repo:**
```yaml
name: Create Repository Based on Issue

on:
  issues:
    types: [opened, labeled]

jobs:
  check_issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Trigger')
    steps:
      - name: Check if issue contains the trigger word
        run: echo "Issue contains 'Trigger'. Proceeding with review request."

  add_reviewer:
    runs-on: ubuntu-latest
    needs: check_issue
    steps:
      - name: Add Reviewer
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              assignees: ['x']
            })

  create_repo:
    runs-on: ubuntu-latest
    needs: add_reviewer
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'approved' }}
    steps:
      - name: Parse Issue for Repo Name
        id: parse
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueBody = context.payload.issue.body;
            const repoNameMatch = issueBody.match(/Repository Name:\s*([^\n\r]+)/m);
            if (repoNameMatch) {
              return repoNameMatch[1].trim();
            }
            throw new Error('Repository name not found in issue body');

      - name: Create repository
        env:
          REPO_NAME: ${{ steps.parse.outputs.result }}
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
        run: |
          gh repo create orgo/$REPO_NAME --public --description "New repo created via automation"
          gh api -X PUT /repos/orgo/$REPO_NAME/collaborators/${{ github.event.issue.user.login }} -f permission=admin
```
